##### Code by S. Jang
##### Last updated: 2026-01-06
##### Code definition: Configuration parameters for 16S_rRNA_metagenomics analysis

project:
  name : "16S_rRNA_metagenomics"
  # root: "/home/promethion/test/16s_metagenomics"
  #root : "/home/mbt/jsy/project/16s_metagenomics"
  root : "/Users/celina/Desktop/project/16s_metagenomics/"

defaults:
  log_base_rel: "Logfiles"

qc_runs:
  raw:
    label: "raw"
    dir_in_rel: "Rawdata"
    dir_out_rel: "00.qc/raw"
    name_strip_suffixes: []
  trimmed:
    label: "post_cutadapt"
    dir_in_rel: "01.cutadapt"
    dir_out_rel: "00.qc/post_cutadapt"
    name_strip_suffixes: ["_trimmed"]
  filtered:
    label: "post_chopper"
    dir_in_rel: "02.chopper"
    dir_out_rel: "00.qc/post_chopper"
    name_strip_suffixes: ["_trimmed_filtered"]

nanocomp_qc:
  runs: ["raw", "trimmed", "filtered"]
  job_limit: 1
  threads: 10
  input_ext: "fastq"
  plot: "false"  
  #formats: "png" #if plot={violin,box,ridge}

chopper_filter:
  dir_in_rel: "01.cutadapt"
  dir_out_rel: "02.chopper"
  job_limit: 20
  threads: 5
  quality: 12
  minlength: 1200
  maxlength: 1800
  input_ext: "fastq"

emu_profile:
  dir_in_rel: "02.chopper"
  dir_out_rel: "03.emu"
  job_limit: 15
  threads: 4
  db_rel: "database/emu/rdp"
  min_abundance: "0.0001"
  extra: "--type map-ont --keep-counts"
  input_ext: "fastq"

taxonomy_split:
  dir_in_rel: "03.emu/final"
  dir_out_rel: "04.split_taxonomy"
